version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
      - "5038:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProductsDB;User=root;Password=MyPassword123!;
    depends_on:
      - db

  frontend:
    build:
      context: ./src/ClientApp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api
    depends_on:
      - api

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MyPassword123!
      MYSQL_DATABASE: ProductsDB
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: