services:
  api:
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
      - "5038:5038"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=ProductsDB;User=root;Password=123456;
    depends_on:
      - db
  frontend:
    build:
      context: ./src/ClientApp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api
    depends_on:
      - api
  db:
    image: mysql:8.0
    container_name: database-testing
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ProductsDB
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}